package com.epam.jmp.concurrency.db;

import com.epam.jmp.concurrency.model.dao.HsqldbNewsDao;
import com.epam.jmp.concurrency.model.dao.NewsMapper;

public final class TablesCreator {

	public static void main(String[] args) {
		/*JdbcTemplate jdbc = Jdbc.INST.getTemplate();
		jdbc.execute("DROP TABLE news IF EXISTS");
		jdbc.execute("CREATE TABLE news(id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, title VARCHAR(256), short_text VARCHAR(512), full_text VARCHAR(2048))");*/
		HsqldbNewsDao newsDao = new HsqldbNewsDao();
		newsDao.setJdbc(Jdbc.INST.getTemplate());
		newsDao.setNewsMapper(new NewsMapper());
		/*News news = new News();
		news.setTitle("title");
		news.setShortText("short_text");
		news.setFullText("full_text");
		newsDao.mergeNews(news);*/
		newsDao.getNews().forEach(news -> System.out.println(news));
	}

}