package com.epam.jmp.concurrency.db;

import org.springframework.jdbc.core.JdbcTemplate;

public final class TablesCreator {

	public static void main(String[] args) {
		JdbcTemplate jdbc = Jdbc.INST.getTemplate();
		jdbc.execute("DROP TABLE news IF EXISTS");
		jdbc.execute("CREATE TABLE news(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(256), short_text VARCHAR(512), full_text VARCHAR(2048))");
	}

}
