package com.epam.jmp.concurrency.db;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;

import com.epam.jmp.concurrency.config.ConcurrencyConfig;
import com.epam.jmp.concurrency.model.News;
import com.epam.jmp.concurrency.model.dao.NewsDao;

public final class TablesCreator {

	public static void main(String[] args) {
		ApplicationContext context = new AnnotationConfigApplicationContext(ConcurrencyConfig.class);
		NewsDao newsDao = context.getBean(NewsDao.class);
		JdbcTemplate jdbc = context.getBean(JdbcTemplate.class);

		jdbc.execute("DROP TABLE news IF EXISTS");
		jdbc.execute("CREATE TABLE news(id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, title VARCHAR(256), short_text VARCHAR(512), full_text VARCHAR(2048))");

		News news = new News();
		news.setTitle("title");
		news.setShortText("short_text");
		news.setFullText("full_text");
		newsDao.mergeNews(news);
		newsDao.getNews().forEach(System.out::println);
	}

}